Repository redhat-appstudio/rhtap-installer, pull requests merged in 2024-04, with the labels that each got.

#96 Rename chart
  Chart.yaml
  bin/make.sh
  templates/namespace/developer/configure.yaml
  templates/openshift-gitops/includes/_argocd.tpl
  templates/openshift-gitops/includes/_configure.tpl
  templates/openshift-gitops/includes/_test.tpl
  test/data/helm-chart/template.yaml
  test/data/manifests/gitops/namespace.yaml
Labels: approved

#95 Use certified images
  templates/acs/includes/_configure.tpl
  templates/configure.yaml
  templates/developer-hub/includes/_configure.tpl
  templates/namespace/includes/_configure.tpl
  templates/namespace/includes/_test.tpl
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  templates/namespace/includes/tekton/_pe_info_task.tpl
  templates/namespace/includes/tekton/_test.tpl
  templates/openshift-gitops/includes/_configure.tpl
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-pipelines/includes/_tekton-pipelines_wait.tpl
  templates/openshift-pipelines/includes/_test.tpl
  templates/quay/includes/_configure.tpl
  templates/test.yaml
  templates/trusted-artifact-signer/includes/_configure.tpl
  templates/trusted-profile-analyzer/includes/_configure.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#97 Rename chart
  Chart.yaml
  bin/make.sh
  templates/namespace/developer/configure.yaml
  templates/openshift-gitops/includes/_argocd.tpl
  templates/openshift-gitops/includes/_configure.tpl
  templates/openshift-gitops/includes/_test.tpl
  test/data/helm-chart/template.yaml
  test/data/manifests/gitops/namespace.yaml
Labels: approved

#94 Add 'certify' command to make.sh
  bin/make.sh
Labels: lgtm, approved

#100 Updated Dockerfile to install both of cosign and syft
  ci/Dockerfile
Labels: lgtm, approved

#93 1.0/productization
  Chart.yaml
  templates/tests/test.yaml
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#92 Getting ready to publish the chart
  Chart.yaml
  templates/tests/test.yaml
  test/data/helm-chart/template.yaml
Labels: approved

#104 [main] Fix issue with long names
  bin/make.sh
  templates/configure.yaml
  templates/developer-hub/includes/_configure.tpl
  templates/namespace/developer/configure.yaml
  templates/namespace/includes/_configure.tpl
  templates/namespace/includes/tekton/_dev_setup_pipelinerun.tpl
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  templates/namespace/includes/tekton/_pe_info_pipelinerun.tpl
  templates/namespace/includes/tekton/_pe_info_task.tpl
  templates/openshift-gitops/includes/_argocd.tpl
  templates/openshift-gitops/includes/_configure.tpl
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-gitops/includes/tekton/_argocd_login_check.tpl
  templates/openshift-pipelines/includes/_configure.tpl
  templates/trusted-artifact-signer/includes/_configure.tpl
  templates/trusted-artifact-signer/includes/_securesign.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#103 [release-1.0] Fix issue with long names
  bin/make.sh
  templates/configure.yaml
  templates/developer-hub/includes/_configure.tpl
  templates/namespace/developer/configure.yaml
  templates/namespace/includes/_configure.tpl
  templates/namespace/includes/tekton/_dev_setup_pipelinerun.tpl
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  templates/namespace/includes/tekton/_pe_info_pipelinerun.tpl
  templates/namespace/includes/tekton/_pe_info_task.tpl
  templates/openshift-gitops/includes/_argocd.tpl
  templates/openshift-gitops/includes/_configure.tpl
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-gitops/includes/tekton/_argocd_login_check.tpl
  templates/openshift-pipelines/includes/_configure.tpl
  templates/trusted-artifact-signer/includes/_configure.tpl
  templates/trusted-artifact-signer/includes/_securesign.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#106 [main] Rename chart to satisfy the new naming convention
  Chart.yaml
  templates/tests/test.yaml
  test/data/helm-chart/template.yaml
Labels: approved

#102 Rename chart to satisfy the new naming convention
  Chart.yaml
  templates/tests/test.yaml
  test/data/helm-chart/template.yaml
  test/data/manifests/gitops/namespace.yaml
Labels: approved

#101 Added healthy validation for TPA and TAS
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-pipelines/includes/_test.tpl
  templates/tests/test.yaml
  templates/trusted-artifact-signer/includes/_test.tpl
  templates/trusted-profile-analyzer/includes/_test.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#108 Fix certify command
  bin/make.sh
Labels: needs-rebase, approved

#113 Fix for DH 1.1.1
  templates/developer-hub/includes/_configure.tpl
  templates/developer-hub/includes/configure/_configure_tls.tpl
  templates/developer-hub/quay-token.yaml
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#111 Improve subscriptions management
  templates/openshift-gitops/subscription.yaml
  templates/openshift-pipelines/subscription.yaml
  templates/trusted-artifact-signer/subscription.yaml
  test/data/helm-chart/template.yaml
Labels: approved

#115 Pin DH version to 1.1.x
  templates/developer-hub/includes/_configure.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#117 fixed issue that cannot create Securesign instance correctly
  templates/trusted-artifact-signer/includes/_securesign.tpl
Labels: lgtm, approved

#119 Revert 'Pin DH version to 1.1.x'
  templates/developer-hub/includes/_configure.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#120 Upgrade TAS to 1.0.0
  templates/trusted-artifact-signer/subscription.yaml
  test/data/helm-chart/template.yaml
Labels: approved

#124 Clean-up
  README.md
  templates/acs/includes/_configure.tpl
  templates/configure.yaml
  templates/developer-hub/includes/configure/_configure_tls.tpl
  templates/namespace/includes/_test.tpl
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-pipelines/includes/_test.tpl
  templates/quay/includes/_configure.tpl
  templates/quay/subscription.yaml
  templates/trusted-artifact-signer/includes/_test.tpl
  templates/trusted-profile-analyzer/includes/_test.tpl
  test/data/helm-chart/template.yaml
  test/data/manifests/gitops/namespace.yaml
  test/data/manifests/pipelines/repository.yaml
Labels: approved

#125 Clean-up
  README.md
  templates/acs/includes/_configure.tpl
  templates/configure.yaml
  templates/namespace/includes/_test.tpl
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-pipelines/includes/_test.tpl
  templates/quay/includes/_configure.tpl
  templates/quay/subscription.yaml
  templates/trusted-artifact-signer/includes/_test.tpl
  templates/trusted-profile-analyzer/includes/_test.tpl
  test/data/helm-chart/template.yaml
  test/data/manifests/gitops/namespace.yaml
  test/data/manifests/pipelines/repository.yaml
Labels: approved

#126 Install cosign and syft in docker container
  ci/Dockerfile
Labels: approved

#127 fixed tpa test issue
  templates/namespace/includes/_test.tpl
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-pipelines/includes/_test.tpl
  templates/trusted-artifact-signer/includes/_test.tpl
  templates/trusted-profile-analyzer/includes/_test.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#109 Fix 'make.sh values'
  bin/make.sh
Labels: approved

#131 Fix 'make.sh values'
  bin/make.sh
Labels: approved

#132 Fix 'make.sh values'
  bin/make.sh
Labels: approved

#133 Fix 'make.sh values'
  bin/make.sh
Labels: approved

#134 fix issue that cannot handle GITHUB__APP__PRIVATE_KEY variable properly
  bin/make.sh
Labels: approved

#136 Upgrade TPA to 1.0.0-TP1
  templates/trusted-profile-analyzer/includes/_configure.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#123 Use /tmp as the workdir in containers
  templates/developer-hub/includes/_configure.tpl
  templates/namespace/includes/_configure.tpl
  templates/namespace/includes/_test.tpl
  templates/openshift-gitops/includes/_configure.tpl
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-pipelines/includes/_configure.tpl
  templates/openshift-pipelines/includes/_test.tpl
  templates/trusted-artifact-signer/includes/_configure.tpl
  templates/trusted-artifact-signer/includes/_test.tpl
  templates/trusted-profile-analyzer/includes/_configure.tpl
  templates/trusted-profile-analyzer/includes/_test.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#138 fixed rhtap release name
  bin/make.sh
  templates/openshift-gitops/includes/_configure.tpl
Labels: lgtm, approved

#144 install diff package in Dockerfile
  ci/Dockerfile
Labels: lgtm, approved

#145 updated template.yaml
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#148 Update README.md
  README.md
Labels: approved

#150 Update README.md
  README.md
Labels: lgtm, approved

#151 Update README.md
  README.md
Labels: lgtm

#158 Add PE info for GitLab OAuth configuration
  templates/namespace/includes/tekton/_pe_info_task.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#157 Beautify tests
  templates/namespace/includes/_test.tpl
  templates/namespace/includes/tekton/_test.tpl
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-pipelines/includes/_test.tpl
  templates/trusted-artifact-signer/includes/_test.tpl
  templates/trusted-profile-analyzer/includes/_test.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#156 Remove 'delete' command in make.sh
  bin/make.sh
Labels: approved
