Repository redhat-appstudio/rhtap-installer, pull requests merged in 2024-02, with the labels that each got.

#4 enable techdoc plugins
  test/data/helm-chart/template.yaml
  values.yaml
Labels: lgtm, approved

#6 Add values to help with troubleshooting
  .gitignore
  templates/acs/includes/_configure.tpl
  templates/configure.yaml
  templates/developer-hub/includes/_configure.tpl
  templates/namespace/includes/_configure.tpl
  templates/openshift-gitops/includes/_configure.tpl
  templates/openshift-pipelines/includes/_configure.tpl
  templates/quay/includes/_configure.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: lgtm

#10 PLNSRVCE-1582: Trusted Profile Analyzer
  templates/configure.yaml
  templates/trusted-profile-analyzer/includes/_configure.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: lgtm

#12 Update Developer Hub to 1.1-*-CI
  Chart.lock
  Chart.yaml
  templates/trusted-profile-analyzer/includes/_configure.tpl
  test/data/helm-chart/template.yaml
  test/e2e.sh
  values.yaml
Labels: lgtm, approved

#13 Set version: 0.8.0
  Chart.yaml
Labels: approved

#14 Install DH independently
  Chart.lock
  Chart.yaml
  bin/make.sh
  templates/developer-hub/includes/_configure.tpl
  test/data/helm-chart/template.yaml
  test/e2e.sh
  values.yaml
Labels: approved

#16 Enable DH Tekton plugin
  templates/developer-hub/includes/_configure.tpl
  templates/developer-hub/includes/configure/_plugin_kubernetes.tpl
  templates/developer-hub/serviceaccount.yaml
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#17 Enable DH Topology plugin
  templates/developer-hub/includes/_configure.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#15 Fix certificate issues in DH
  templates/developer-hub/includes/_configure.tpl
  templates/developer-hub/includes/configure/_configure_tls.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#19 Enable routes in DH topology plugin
  values.yaml
Labels: approved

#18 Install TAS Subscription
  README.md
  templates/configure.yaml
  templates/trusted-artifact-signer/includes/_configure.tpl
  templates/trusted-artifact-signer/includes/_securesign.tpl
  templates/trusted-artifact-signer/subscription.yaml
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#22 Fix all shellcheck errors
  bin/make.sh
  test/e2e.sh
Labels: approved

#23 Improve 'make.sh values'
  bin/make.sh
  test/e2e.sh
Labels: lgtm, approved

#24 Improve UX by providing PE with the logs' URL
  templates/NOTES.txt
Labels: approved
