Repository redhat-appstudio/rhtap-installer, pull requests merged in 2024-03, with the labels that each got.

#25 Fix most yamllint errors
  Chart.yaml
  bin/make.sh
  ci/config/yamllint.yaml
  templates/configure.yaml
  templates/developer-hub/quay-token.yaml
  templates/developer-hub/serviceaccount.yaml
  templates/openshift-gitops/namespace.yaml
  templates/openshift-gitops/subscription.yaml
  templates/openshift-pipelines/subscription.yaml
  templates/serviceaccount.yaml
  templates/test.yaml
  templates/trusted-artifact-signer/subscription.yaml
  test/data/helm-chart/template.yaml
  test/data/manifests/gitops/namespace.yaml
  test/data/manifests/pipelines/repository.yaml
  values.yaml
Labels: approved

#26 RHTAPBUGS-1146: TPA Dependency Bump
  README.md
  bin/make.sh
  templates/trusted-profile-analyzer/includes/_configure.tpl
  values.yaml
Labels: bug, lgtm, approved

#27 Adding QE owners
  OWNERS
Labels: lgtm, approved

#28 Auto configure known developer namespaces
  templates/namespace/developer/configure.yaml
  templates/namespace/includes/_configure.tpl
  templates/namespace/includes/tekton/_dev_setup_pipelinerun.tpl
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  templates/namespace/includes/tekton/_pe_info_task.tpl
  templates/namespace/includes/tekton/_test_pipeline.tpl
  templates/namespace/namespace.yaml
  test/data/helm-chart/template.yaml
Labels: approved

#21 Upgrade Openshift Pipelines from 1.13 to 1.14
  test/data/helm-chart/template.yaml
  values.yaml
Labels: lgtm, approved

#29 Auto configure known developer namespaces
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#30 Auto configure known developer namespaces
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#31 Add a dockerfile to install test tools in openshift CI
  ci/Dockerfile
Labels: lgtm, approved

#33 Bug fixes
  templates/developer-hub/includes/_configure.tpl
  templates/developer-hub/includes/configure/_plugin_kubernetes.tpl
  templates/namespace/developer/configure.yaml
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  templates/openshift-pipelines/includes/_configure.tpl
  templates/trusted-profile-analyzer/includes/_configure.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#34 Enable DH Quay plugin
  test/data/helm-chart/template.yaml
  values.yaml
Labels: lgtm, approved

#35 Bug fixes in make.sh
  README.md
  bin/make.sh
Labels: approved

#36 Improve 'bin/make.sh values'
  bin/make.sh
Labels: approved

#37 Add GitLab support
  bin/make.sh
  values.yaml
Labels: approved

#38 Plain text value for quay authentication data
  bin/make.sh
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#40 Fix DH TLS reconfiguration bug
  bin/make.sh
  templates/developer-hub/includes/configure/_configure_tls.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#41 Fix argocd namespace configuration
  templates/namespace/developer/configure.yaml
  templates/namespace/namespace.yaml
  test/data/manifests/gitops/namespace.yaml
Labels: approved

#42 update rox secret keys
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#43 rename rox-api-central-endpoint to rox-api-endpoint
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#44 add " rox-api-endpoint" key also in developer namespace
  templates/namespace/includes/tekton/_dev_setup_task.tpl
Labels: lgtm, approved

#39 RHTAPBUGS-1151: ArgoCD Application-Controller Memory Limit
  templates/openshift-gitops/includes/_argocd.tpl
  values.yaml
Labels: lgtm, approved

#45 Improve 'bin/make.sh values'
  bin/make.sh
  test/data/helm-chart/template.yaml
Labels: approved

#46 Link quay token to default account in developer namespaces
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#47 fixed issue of yamlint cli not found
  ci/Dockerfile
Labels: lgtm, approved

#49 Instanciate rhtap-app-* namespaces by default
  templates/namespace/developer/configure.yaml
  templates/namespace/includes/_configure.tpl
  templates/namespace/namespace.yaml
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#50 Remove ACS tekton tasks
  templates/acs/includes/_configure.tpl
  templates/acs/includes/tekton/_acs_deploy_check.tpl
  templates/acs/includes/tekton/_acs_image_check.tpl
  templates/acs/includes/tekton/_acs_image_scan.tpl
  templates/namespace/includes/tekton/_test_pipeline.tpl
Labels: approved

#52 Impove DH deployment process
  Chart.yaml
  templates/developer-hub/includes/_configure.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#54 RHTAPBUGS-1149: Expose MinIO PVC Size
  values.yaml
Labels: lgtm, approved

#56 Upgrade Developer Hub to 1.1.0 GA
  templates/developer-hub/includes/_configure.tpl
  templates/developer-hub/quay-token.yaml
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#58 Fix hardcoded namespace issue
  templates/developer-hub/includes/configure/_configure_tls.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#59 Improve DH deployment process
  templates/developer-hub/includes/_configure.tpl
  templates/developer-hub/includes/configure/_configure_tls.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#60 Fix issue with app namespaces configuration
  templates/namespace/developer/configure.yaml
  templates/namespace/includes/_configure.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#57 Add checkov in GitHub Actions
  .github/.workflows/checkov.yaml
Labels: lgtm, approved

#61 Fix issue with namespace setup
  bin/make.sh
  templates/namespace/developer/configure.yaml
  templates/namespace/includes/_configure.tpl
  templates/namespace/namespace.yaml
  test/data/helm-chart/template.yaml
Labels: approved

#62 Add cosign signing public key to app namespaces
  templates/namespace/includes/_configure.tpl
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#63 fix issue with redeployment creating namespace
  templates/namespace/developer/configure.yaml
Labels: lgtm, approved

#53 Add Sonar
  .github/workflows/build.yml
  sonar-project.properties
Labels: lgtm, approved

#65 Fix DH deployment update
  templates/developer-hub/includes/_configure.tpl
  templates/developer-hub/includes/configure/_configure_tls.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#64 Fix components guards
  templates/developer-hub/includes/_configure.tpl
  templates/openshift-gitops/subscription.yaml
  templates/openshift-pipelines/subscription.yaml
  test/data/helm-chart/template.yaml
Labels: approved

#67 Add argocd cli to Openshift CI test container
  ci/Dockerfile
Labels: approved

#72 Upgrade GitOps to 1.12
  templates/openshift-gitops/includes/_test.tpl
  templates/openshift-pipelines/includes/_test.tpl
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#73 Enable production mode in DH
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#74 Init version 0.11.0
  Chart.yaml
  test/data/helm-chart/template.yaml
Labels: approved

#75 yamllint ignores templates directory
  ci/config/yamllint.yaml
Labels: lgtm, approved

#76 Improve gitops/argocd test
  templates/openshift-gitops/includes/_test.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#78 Add 'uninstall' command to bin/make.sh
  bin/make.sh
Labels: approved

#80 Install kubectl cli
  ci/Dockerfile
Labels: lgtm, approved

#83 Use RH images during install/configuration
  templates/namespace/includes/tekton/_pe_info_task.tpl
  templates/openshift-pipelines/includes/_tekton-pipelines_wait.tpl
  templates/quay/includes/_configure.tpl
  test/data/helm-chart/template.yaml
Labels: approved

#88 Fix security issue in Pipelines As Code
  templates/openshift-pipelines/includes/_tekton-config.tpl
  test/data/helm-chart/template.yaml
Labels: lgtm, approved

#87 Deploy the pre-release versions of DH
  templates/developer-hub/includes/_configure.tpl
  templates/developer-hub/quay-token.yaml
  test/data/helm-chart/template.yaml
  values.yaml
Labels: approved

#90 Add username to GitLab secret
  templates/namespace/includes/tekton/_dev_setup_task.tpl
  test/data/helm-chart/template.yaml
Labels: approved
